 version: 2
 jobs:
   build:
     docker:
       - image: mcr.microsoft.com/dotnet/core/sdk:2.1
     steps:
       - checkout
       - run: 
           name: Restore packages
           command:
             dotnet restore src/Minimarket.API/
       - run: 
           name: Build App
           command:
             dotnet build src/Minimarket.API/